### ISSUE TITLE
code_object() got an unexpected keyword argument 'compiler_kwds'

### ISSUE THREAD

**Issue by Helloworld-Le** [brian-team/brian2genn#84]
HI，
After running the provided test from GeNN documentation， I got an error ： 

```
_**_**### _INFO       The following preferences have been changed for Brian2GeNN, reset them manually if you use a different device later in the same script: codegen.loop_invariant_optimisations, core.network.default_schedule [brian2.devices.genn]
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_vqmdhw.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_qi7xpG.py Thanks! [brian2]
Traceback (most recent call last):
  File "/home/le/Python_Plus/PycharmProjects/Genn/genn_test.py", line 13, in <module>
    Ce.connect(p=0.02)
  File "/home/le/.local/lib/python2.7/site-packages/brian2/core/base.py", line 276, in device_override_decorated_function
    return func(*args, **kwds)
  File "/home/le/.local/lib/python2.7/site-packages/brian2/synapses/synapses.py", line 1400, in connect
    namespace=namespace, level=level+2)
  File "/home/le/.local/lib/python2.7/site-packages/brian2/synapses/synapses.py", line 1706, in _add_synapses_generator
    run_namespace=namespace)
  File "/home/le/.local/lib/python2.7/site-packages/brian2/codegen/codeobject.py", line 416, in create_runner_codeobj
    compiler_kwds=compiler_kwds
TypeError: code_object() got an unexpected keyword argument 'compiler_kwds'_**_**_
```

Do you have any idea how to solve it?

**Comment by mstimberg** [comment]
Hi. Apologies, this was due to a change in Brian 2 which was not yet taken into account in the released version of Brian2GeNN (the development version was working, though). I just made a new release (Brian2GeNN 1.3), please update (or simply remove and reinstall) your Brian2GeNN installation with:
```
pip install --upgrade --upgrade-strategy only-if-needed brian2genn
```
and try again.

**Comment by Helloworld-Le** [comment]
Hi, thanks for your prompt reply and work!

**Comment by mstimberg** [comment]
You are welcome! I assume this means it is working for you now, please feel free to re-open this issue if it is not.

**Comment by mstimberg** [comment]
@Helloworld-Le There were actually more incompatibilities with Brian's latest version, please make sure to update yet another time, I just made a new 1.3.1. release with additional fixes.
